name: Java CI

on: [ push, pull_request ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout latest code
        uses: actions/checkout@v3
        
      - name: Make gradlew executable
        run: chmod +x ./gradlew

      - name: Set up JDK 17
        uses: actions/setup-java@v2
        with:
          distribution: 'zulu'
          java-version: 17

      - name: Build with Gradle
        run: ./gradlew build --full-stacktrace

      - name: Check Folder
        run: ls
      # 上传完整工作目录（包含所有生成文件）
      - name: Upload Entire Workspace
        uses: actions/upload-artifact@v4
        with:
          name: full-environment
          path: ${{ github.workspace }}
          retention-days: 7  # 自动保留天数（可选）
        
      - uses: actions/upload-artifact@v4
        with:
          name: Triton-Core
          path: core/build/libs

      - uses: actions/upload-artifact@v4
        with:
          name: Triton-API
          path: api/build/libs
